{% set name = "pyhmmer" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/63/1a/fd0ed657605ef315486b0769acc1a43d3f6a37b13ea9b606a46e300617d8/pyhmmer-0.2.0.tar.gz
  sha256: e532f64418d1cd43340d0615dc133c21e3d8128f43723c6502a92e1986c6ebd8

build:
  number: 0
  skip: True  #[py2k or win or osx]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - setuptools >=46.4
  run:
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/althonos/pyhmmer
  license: MIT
  license_file: COPYING
  summary: Cython bindings and Python interface to HMMER3.
  doc_url: https://pyhmmer.readthedocs.io

extra:
  recipe-maintainers:
    - althonos
  identifiers:
    - DOI:10.5281/zenodo.4270012
